var albumEditorLabels = {
    "View source": "Toon broncode",
    "[Style]": "[Stijl]",
    "Paragraph": "Paragraaf",
    "Heading 1": "Kop 1",
    "Heading 2": "Kop 2",
    "Heading 3": "Kop 3",
    "Heading 4": "Kop 4",
    "Heading 5": "Kop 5",
    "Heading 6": "Kop 6",
    "Blockquote": "Blokcitaat",
    "Preformatted": "Voorgeformatteerd",
    "Enter link URL:": "Geef link URL:",
    "Enter image URL:": "Geef afbeelding URL:",
    "You must provide an URL!": "U moet een URL opegeven!",
    "Enter alternate text:": "Geef alternatieve tekst:",
    "You must provide alternate text!": "U moet alternatieve tekst opgeven!",
    "Number of rows:": "Aantal rijen (exclusief de kop):",
    "Number of columns:": "Aantal kolommen:",
    "You must specify at least one row!": "U moet minstens 1 rij opgeven!",
    "You must specify at least one column!": "U moet minstens 1 kolom opgeven!",
    "Highlight": "<strong>Vetgedrukt</strong>",
    "Subscript": "S<sub>ubscript</sub>",
    "Superscript": "S<sup>uperscript</sup>",
    "Add link": "Link toevoegen",
    "Remove link": "Link verwijderen",
    "Add image": "Afbeelding toevoegen",
    "Add unordered list": "Opsomming toevoegen",
    "Add ordered list": "Nummering toevoegen",
    "Add table with horizontal header": "Voeg tabel toe met horizontale kop",
    "Add table with vertical header": "Voeg tabel toe met verticale kop",
    "Add table without border": "Voeg tabel toe zonder randen"
};

var pictureEditorLabels = albumLabels;
